version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: rastad_postgres
    restart: always
    environment:
      POSTGRES_DB: rastad_ai
      POSTGRES_USER: rastad_user
      POSTGRES_PASSWORD: rastad_pass
    ports:
      - "5433:5432"
    volumes:
      - rastad_postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: rastad_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rastad_user:rastad_pass@postgres:5432/rastad_ai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./knowledge_base:/app/knowledge_base

volumes:
  rastad_postgres_data:
